# Lightweight Node.js image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy dependency files and install
COPY package*.json ./
RUN npm install

# Copy the rest of the application
COPY . ./


# Start the server
CMD ["node", "src/servyou.cjs"]
