name: Copy Back to VPS
on:
  push:
    branches: [prod]

jobs:
  copy-back:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy ./back to VPS
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY_NO_PHRASE }}
          port: 22
          source: "back/**"
          target: "/var/www/html/codeurbase/back"
          strip_components: 1
          rm: false