name: Build & Deploy Prod Svelte

on:
  push:
    branches:
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3️⃣ Installer les dépendances
      - name: Install dependencies
        run: npm ci
        working-directory: ./front

      # 4️⃣ Builder l’app avec les variables d’env
      - name: Build Svelte
        run: npm run build
        working-directory: ./front
        env:
          VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
          VITE_N8N_URL: ${{ secrets.VITE_N8N_URL }}

      # 5️⃣ Déploiement (copie du build)
      - name: Copy Svelte build to VPS
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY_NO_PHRASE }}
          port: 22
          source: "./front/dist/**"
          target: "/var/www/html/codeurbase/"
          rm: false
